### ISSUE TITLE
Failing to install on Ubuntu 16.04

### ISSUE THREAD

**Issue by amirbaer** [defi-org-code/ethereumjs-jump-blocks#2]
Hi!

Getting an error when trying to install on an Ubuntu 16.04:
`Error: Command failed: npm run postinstall
npm ERR! /usr/bin/env: ‘bash -e’: No such file or directory`
 
![image](https://user-images.githubusercontent.com/4663287/129516673-216d3b9c-feab-49e5-ae4f-4f6435846d6f.png)

Complete log:
[2021-08-16T05_43_34_570Z-debug.log](https://github.com/defi-org-code/ethereumjs-hooks/files/6990051/2021-08-16T05_43_34_570Z-debug.log)

Thank you!

**Comment by DanielZlotin** [comment]
@amirbaer plz confirm with `0.1.6`
